### ISSUE TITLE
Version 1.0.5 is not referenced in version capability

### ISSUE THREAD

**Issue by aidan-melen** [sonatype-nexus-community/nexus-repository-r#105]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
document what Nexus Version the R plugin verison 1.0.5 is compatible with.

* **How could we solve this issue? (Not knowing is okay!)**

add this to [nexus version compatibility](https://github.com/sonatype-nexus-community/nexus-repository-r#compatibility-with-nexus-repository-manager-3-versions) in the README.md:

```1.0.5 >= 3.19.1-01```

I have tested this combo and it works.

**Comment by joedragons** [comment]
@bhamail Looks like you released?

**Comment by bhamail** [comment]
The changes in 1.0.5 that were released on Sept 17 did not increase the NXRM version dependency. Plugin v1.0.5 was still built against NXRM 3.18.0-01 (the same as v1.0.4). The implication of the "1.0.4 >= <NXRM version>" is: we expect the plugin to work fine with newer versions of NXRM - hence the ">=".

It is excellent to post the information that the plugin 1.0.5 is working fine in a newer NXRM version - and Thank You for sharing this. (We might want a better way to gather and share this sort if information about known working versions). However, that table is not meant to be an exhaustive list of known working combinations, but rather "minimum" NXRM version needed to build the plugin.
 
Not directly related: One oddity that has caused confusion in the past is even after we release the plugin, the pom.xml version showing in the GitHub source is the "old" (just release) version. I'm working on improvements to the CI / Plugin Release process that would automatically increment the pom version to 1.0.6-SNAPSHOT...
