### ISSUE TITLE
uploading to sonatype nexus

### ISSUE THREAD

**Issue by ctr0603** [sonatype-nexus-community/nexus-repository-r#20]
I am trying to upload example_1.0.0.tgz to r-hosted as per the instruction provided by you but i am getting curl: (52) Empty reply from server please let me know if i am doing anything wrong

curl --upload-file example_1.0.0.tgz -v -u admin:admin123 http://localhost:8081/repository/r-hosted/example_1.0.0.tgz
* About to connect() to proxy 127.0.0.1 port 3128 (#0)
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 3128 (#0)
* Server auth using Basic with user 'admin'
> PUT http://localhost:8081/repository/r-hosted/example_1.0.0.tgz HTTP/1.1
> Authorization: Basic YWRtaW46YWRtaW4xMjM=
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:8081
> Accept: */*
> Proxy-Connection: Keep-Alive
> Content-Length: 0
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< Connection: close
* Empty reply from server
* Closing connection #0
curl: (52) Empty reply from server

**Comment by doddi** [comment]
You need to specify a subfolder to host the asset into, for example:
curl --upload-file example_1.0.0.tgz -v -u admin:admin123 http://localhost:8081/repository/r-hosted/example/example_1.0.0.tgz

**Comment by joedragons** [comment]
@ctr0603 I am closing this to clean out our issue list.  We can reopen if you still have issue.
