### ISSUE TITLE
Installing nexus-repository-r into sonatype/docker-nexus3 container

### ISSUE THREAD

**Issue by afedulov** [sonatype-nexus-community/nexus-repository-r#24]
I am trying to install nexus-repository-r into sonatype/docker-nexus3, but I cannot achieve this with provided installation variants:

1. Karaf console: when inside the docker container ./bin/nexus run complaints that /nexus-data is already in use (locked by the main process of the container)
2. XML-based config: /opt/sonatype/ is not exposed as a persistent volume (as it is the case for nexus-data), so uploading the binary, modifying the settings and restarting the container is not possible without loosing what I've just modified.

Maybe I am missing something, but it seems that plugins and their configuration should be a part of persistent volume (like nexus-data)

I understand that this might be more of an issue with the docker image itself, but I am hoping that maybe someone could recommend a workaround. Also, docker-nexus3 repo has it's Issues section closed, so there is no other place to ask.

**Comment by DarthHater** [comment]
Hi there, I'm doing #27 to sorta make this a lil bit smoother for some people. I think once this is merged it will make it easier to spin up Nexus Repo with R inside of it, and then if you configure that new image to use a volume, all should be used in unison. 

In the README for docker-nexus3 I believe it points you to the public JIRA for Sonatype, the team that manages that repo chose to close it so they could prioritize the Docker work with other Nexus Repo work.

**Comment by mlukaretkyi** [comment]
not relevant anymore
