### ISSUE TITLE
 java.lang.IncompatibleClassChangeError on packages upload

### ISSUE THREAD

**Issue by afedulov** [sonatype-nexus-community/nexus-repository-r#25]
I have installed nexus-repository-r as described in "(most) permanent" setup section. Whenever I do 

`curl -v --user 'admin:admin123' --upload-file package.tgz http://localhost:8081/repository/dslab-r/src/contrib/package.tgz`

The following exception is thrown:

> 2018-02-12 21:31:16,996+0000 ERROR [qtp1359854998-174] *SYSTEM org.sonatype.nexus.internal.web.ErrorPageServlet - Unexpected exception
> java.lang.IncompatibleClassChangeError: Found interface org.sonatype.nexus.repository.storage.Component, but class was expected
> 	at org.sonatype.nexus.repository.r.internal.RHostedFacetImpl.doPutArchive(RHostedFacetImpl.java:162)
> 	at org.sonatype.nexus.transaction.TransactionalWrapper.proceedWithTransaction(TransactionalWrapper.java:56)

Nexus version:                      3.8.0.02
nexus-repository-r version:   1.0.0

**Comment by jlstephens89** [comment]
@afedulov Try updating the parent version in the r pom file to 3.8.0-02 and rebuild. Please share a PR if it fixes your issue.

**Comment by afedulov** [comment]
@jlstephens89 thanks, I've already figured it out. I think adding a one-liner about this in the documentation would be pretty helpful (right now it just proposes to do mvn clean install, regardless of the Nexus version)

**Comment by DarthHater** [comment]
@afedulov I added a line akin to that in the README, does that work for you?

**Comment by afedulov** [comment]
That is helpful! I was thinking about describing manual pom.xml modification according to the version of Nexus right before `mvn clean install` step, but this is obviously more fragile than having breaking dependencies reflected in a separate plugin version.

**Comment by DarthHater** [comment]
Coolio! I'll close this as a result.
