### ISSUE TITLE
Doc update needed

### ISSUE THREAD

**Issue by joedragons** [sonatype-nexus-community/nexus-repository-r#31]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Install

* **What feature or behavior is this required for?**
Documentation

* **How could we solve this issue? (Not knowing is okay!)**
The (most) Permanent Install steps need to be changed. After following those steps the plugin is not loaded and an R repository cannot be created.

* **Anything else?**
From internal JIRA ticket https://issues.sonatype.org/browse/NEXUS-13418

**Comment by DarthHater** [comment]
This is likely a result of moving npm to public, I'll take a gander today. Thanks for filing this @joedragons !

**Comment by bhamail** [comment]
I think we should head in this direction with simpler [Dockerfile example](https://github.com/sonatype-nexus-community/nexus-format-archetype/blob/master/src/test/resources/projects/it1/reference/Dockerfile).

**Comment by aornatovskyy** [comment]
Will be fixed in the Nexus Repository Manager 3.20.0

**Comment by aornatovskyy** [comment]
@joedragons  can we close this one what do you think?

**Comment by joedragons** [comment]
Yep thanks!
