### ISSUE TITLE
r is not present in list of formats for search

### ISSUE THREAD

**Issue by joedragons** [sonatype-nexus-community/nexus-repository-r#36]
* **What are you trying to do?**
Search

* **What feature or behavior is this required for?**
I noticed there's no left nav "format" similar to maven and nuget by default, even when you have r contents populated.

* **How could we solve this issue? (Not knowing is okay!)**
On creation, have there be a left nav search item similar to the other formats.  Could also have custom metadata fields if desired but not required.

* **Anything else?**
![screen shot 2018-05-17 at 5 27 38 pm](https://user-images.githubusercontent.com/9559205/40205305-895aa278-59f9-11e8-91c0-c7aaad96d4ae.png)

**Comment by aornatovskyy** [comment]
Will be fixed in the Nexus Repository Manager 3.20.0

**Comment by joedragons** [comment]
@aornatovskyy I saw this in JIRA, so am fine if you want to close now rather than later.  I did not do so in case you have a system=)

**Comment by aornatovskyy** [comment]
Fixed in the NXRM 3.20.0-04 - R 1.1.1
