### ISSUE TITLE
Windows binary distributions supported?

### ISSUE THREAD

**Issue by kenahoo** [sonatype-nexus-community/nexus-repository-r#41]
In a standard CRAN repository, Windows binaries are stored in a location like `/bin/windows/contrib/$R_VERSION/`.  Is that a supported use case for this plugin?

**Comment by cderv** [comment]
When using the proxy repo, I manage to download windows binary package. If you try to install a package on a windows computer using your nexus repo with `install.packages`, it will download from CRAN the binary and put it correctly in the repo. 
However, I did not try to push a windows binary to a hosted repo. Have you tried yourself to upload to `bin/windows/contrib` and see if it's working ?

**Comment by kenahoo** [comment]
Hi @cderv, I did do some trial and error, and I discovered that if I push a binary (using `curl`) to `/bin/windows/contrib/3.3/PackageName_1.2.3.zip`, it gets indexed correctly and I can use it for a binary install.  It didn't work to push it to `/bin/windows/contrib/3.3/PackageName/PackageName_1.2.3.zip` - it accepted the upload, but it didn't get indexed to end up in the `PACKAGES.gz` file, so it couldn't be installed from R.

**Comment by cderv** [comment]
On CRAN, all the binary are stored in `bin/windows/contrib/<version>/<pkg.zip>, and not in sub-folders. 
As mentioned in [another discussion](https://github.com/sonatype-nexus-community/nexus-repository-r/issues/21#issuecomment-415093122), I think it is possible to support subdirectories but it needs to be taken into account in the generation of _PACKAGES.gz_ or _PACKAGES_ file. It is not standard and correspond to `tools::write_PACKAGES(".", subdirs = TRUE)`. CRAN is not a repository that support subdirectories for examples. 
So I don't know what should be the behaviour of nexus, and if currently this is a bug or not.

**Comment by kenahoo** [comment]
I'm happy with the resolution here, ticket can be closed as far as I'm concerned.
