### ISSUE TITLE
Groovy API to create a R Repository from the "Admin. Execute Script" task

### ISSUE THREAD

**Issue by vernetto** [sonatype-nexus-community/nexus-repository-r#46]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
automating the creation  of a R repository with the Groovy Automation API
This class https://github.com/sonatype/nexus-public/blob/master/plugins/nexus-script-plugin/src/main/java/org/sonatype/nexus/script/plugin/RepositoryApi.java  exposes a repository.create* method for all formats, but of course "r" is not provided.

* **What feature or behavior is this required for?**
automation of configuration

* **How could we solve this issue? (Not knowing is okay!)**

maybe by asking Sonatype  to provide 3 methods (createRHosted, createRProxy, createRGroup) also for R

* **Anything else?**

**Comment by rayxiaonet** [comment]
+1

**Comment by aornatovskyy** [comment]
Thanks for your request.

**Comment by mlukaretkyi** [comment]
REST API added. Closed

**Comment by aornatovskyy** [comment]
**Resolved in the ticket:** https://issues.sonatype.org/browse/NEXUS-22147
