### ISSUE TITLE
ServletException 500 internal error, proxy repo

### ISSUE THREAD

**Issue by srik65** [sonatype-nexus-community/nexus-repository-r#47]
Getting 500 internal with Servlet exception while downloading few R packages from external proxy "R" repos. Nothing logged in nexus log about this. Any suggestions on debugging this please. Currently I'm on R bundle 1.0.0 with nexus 3.13

**Comment by aornatovskyy** [comment]
Hi @srik65,
Do you still have the issue? Would you please provide more information? e.g. what remote server you are using, what version of java you have ...

**Comment by aornatovskyy** [comment]
@srik65  ping

**Comment by srik65** [comment]
> @srik65 ping

sorry for late response, managed to fix.
