### ISSUE TITLE
Error building mvn clean install with maven 3.6.0 on Mac

### ISSUE THREAD

**Issue by DaleBingham** [sonatype-nexus-community/nexus-repository-r#48]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
setup mvn clean install to run clean

* **What feature or behavior is this required for?**
To build the application plugin

* **How could we solve this issue? (Not knowing is okay!)**
What edits to POM or referencing could fix this packaging error.

* **Anything else?**
Error is below: 

`Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-environment) on project nexus-repository-r: Execution enforce-environment of goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce: java.lang.ExceptionInInitializerError: null`

**Comment by DaleBingham** [comment]
`mvn --version` gives you this:

mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: /Users/dalebingham/apache-maven-3.6.0
Java version: 11, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"

**Comment by DarthHater** [comment]
Interesting, thanks for filing this. I'll take a look as soon as I can!

**Comment by bhamail** [comment]
Have you tried building with JDK 1.8? I was able to build with maven 3.6 and jdk 8 on mac os:

```
$ ~/devtools/apache-maven-3.6.0/bin/mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: /Users/bhamail/devtools/apache-maven-3.6.0
Java version: 1.8.0_92, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"
```

I get a whole bunch of build errors when using jdk 11.

**Comment by DarthHater** [comment]
Turns out @bhamail is a genius and reads before replying! JDK 11 is definitely the issue, all of our stuff is currently setup for Java 8. Go ahead and close the issue if that answer satisfies you.

**Comment by aornatovskyy** [comment]
I think the current ticket could be closed. At the same time it will be not relevant for Nexus Repository Manager 3.20.0
