### ISSUE TITLE
unable to access index for repository

### ISSUE THREAD

**Issue by albundy83** [sonatype-nexus-community/nexus-repository-r#5]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Setup R proxy on nexus
* **What feature or behavior is this required for?**
To have nexus correctly proxy requests
* **How could we solve this issue? (Not knowing is okay!)**
Unfortunately, I don't know
* **Anything else?**
I'm using latest nexus OSS release 3.4.0-02

From debian, with my R environment installed, I have followed all the steps to setup correctly nexus-repository-r jar file.
Here the commande I ran:
```R
> install.packages("xts", repos = "http://my_user:my_password@my_nexus_url:8081/nexus/repository/r-all", type="source", dependencies=TRUE)
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://my_user:my_password@my_nexus_url:8081/nexus/repository/r-all/src/contrib:
  cannot open URL 'http://my_user:my_password@my_nexus_url:8081/nexus/repository/r-all/src/contrib/PACKAGES'
Warning message:
package ‘xts’ is not available (for R version 3.2.3) 
```

**Comment by albundy83** [comment]
For what I see, the issue could come from the fact I put user and password in `repos` parameter.
When I don't specify user and password, I see a 401 in my nexus request.log:
```
10.10.0.27 - - [31/Jul/2017:15:29:09 +0200] "GET /nexus/repository/r-all/src/contrib/PACKAGES.gz HTTP/1.0" 401 0 4 "R (3.2.3 x86_64-pc-linux-gnu x86_64 linux-gnu)"
10.10.0.27 - - [31/Jul/2017:15:29:09 +0200] "GET /nexus/repository/r-all/src/contrib/PACKAGES HTTP/1.0" 401 0 2 "R (3.2.3 x86_64-pc-linux-gnu x86_64 linux-gnu)"
```
But when I specify user and password, I don't see any trace of my calls in request.log.

**Comment by DarthHater** [comment]
Thanks for filing this @albundy83 (and hilarious username). I'll take a gander as soon as I can.

**Comment by albundy83** [comment]
Thanks for your help, if you need more details, logs, tests etc ... just ask :)

**Comment by joedragons** [comment]
Is there a reverse proxy or load balancer or anything in front of your repository manager?  I am puzzling why there's nothing in the request.log...it should be there as far as I know and that's a common reason why not.

**Comment by albundy83** [comment]
No, I have a direct access to the nexus

**Comment by screig** [comment]
if you look at the assets tab for this repo is the PACKAGE file there?

**Comment by DarthHater** [comment]
@albundy83 are you using a group? I'm guessing so based on the `r-all` name. What is in the group, if you are using it?

<img width="623" alt="screen shot 2017-08-14 at 9 33 55 am" src="https://user-images.githubusercontent.com/5544326/29283605-eb5e2aee-80d3-11e7-9404-7d81866c089c.png">

That's just with no auth, then I tried auth.

I setup the plugin on 3.5.1 (internal version at the moment), and a proxy, and so far so good. I've created a user `jhesse` with the role of `nx-r-read` which I assigned:

<img width="242" alt="screen shot 2017-08-14 at 9 41 07 am" src="https://user-images.githubusercontent.com/5544326/29283823-bb3b409e-80d4-11e7-9ae6-8726c8509370.png">

I turned off anonymous access to make sure I had things setup right, as well.

```
> install.packages("xts", repos="http://user:pass@localhost:8081/repository/r-proxy")


Warning in install.packages :
  unable to access index for repository http://localhost:8081/repository/r-group/src/contrib:
  cannot download all files
also installing the dependency ‘zoo’

trying URL 'http://user:pass@localhost:8081/repository/r-proxy/bin/macosx/mavericks/contrib/3.3/zoo_1.8-0.tgz'
Content type 'application/x-tgz' length 887574 bytes (866 KB)
==================================================
downloaded 866 KB

trying URL 'http://user:pass@localhost:8081/repository/r-proxy/bin/macosx/mavericks/contrib/3.3/xts_0.10-0.tgz'
Content type 'application/x-tgz' length 711869 bytes (695 KB)
==================================================
downloaded 695 KB
```

(You can ignore the r-group warning, as I've got that setup behind the scenes as the first R repo to hit). 

Being a bit laborious about my setup just in case that's what is hosing your setup.

**Comment by albundy83** [comment]
Hello,
sorry for my late reply (some holidays ... :-) 
I have updated to latest release of nexus (3.5.0-02), I have updated also to the latest version of the plugin R.
Here the capture for the content of `r-all` group (yes I use group):
![screenshot from 2017-08-21 13-49-32](https://user-images.githubusercontent.com/1215213/29517965-cb41d626-8677-11e7-9819-286c5ccb9dda.png)
As you can see, there is no PACKAGE file there ...
I have setup a dedicated user which has the 2 following rights:
`nx-repository-any-read`
`nx2-repository-any-read`

Do you think that the `xx-browse` rights is necessary ?

**Comment by albundy83** [comment]
I have tried to update my role `nx-repository-any-read` with the following content:
![screenshot from 2017-08-21 14-04-15](https://user-images.githubusercontent.com/1215213/29518465-b40b1c68-8679-11e7-95b6-0a30614cfaec.png)

But nothing is different.

**Comment by DarthHater** [comment]
Ok, I get it now! @screig mentioned this indirectly in #10 

Right now the code only has a route (and a mechanism to serve) 1PACKAGES.gz`, nothing for `PACKAGES` itself. 

Adding the ability to pass this through on proxy is relatively trivial, but for Hosted/Group would involve some more work. 

For the route (if you want to implement this), take a gander here:
https://github.com/sonatype/nexus-repository-r/blob/master/src/main/java/org/sonatype/nexus/repository/r/internal/RRecipeSupport.groovy#L116

And here:

https://github.com/sonatype/nexus-repository-r/blob/master/src/main/java/org/sonatype/nexus/repository/r/internal/RProxyRecipe.groovy#L89

You can see that we use something very specific (it looks for routes that match `PACKAGES.gz`).

PR's welcome :)

**Comment by screig** [comment]
Like I mentioned I am no java programmer, so would not know how to debug this, but essentially what you are saying is that it should be like so:

  ```
/**
   * Matcher for gunzipped packages mapping.
   */
  static Builder gz_packagesMatcher() {
    new Builder().matcher(
        LogicMatchers.and(
            new ActionMatcher(GET, HEAD),
            new TokenMatcher('/{path:.+}/PACKAGES.gz')
        ))
  }

  /**
   * Matcher for raw packages mapping.
   */
  static Builder raw_packagesMatcher() {
    new Builder().matcher(
        LogicMatchers.and(
            new ActionMatcher(GET, HEAD),
            new TokenMatcher('/{path:.+}/PACKAGES')
        ))
  }

```
and then 

```

    builder.route(gz_packagesMatcher()
        .handler(timingHandler)
        .handler(assetKindHandler.rcurry(PACKAGES))
        .handler(securityHandler)
        .handler(exceptionHandler)
        .handler(handlerContributor)
        .handler(negativeCacheHandler)
        .handler(partialFetchHandler)
        .handler(contentHeadersHandler)
        .handler(unitOfWorkHandler)
        .handler(proxyHandler)
        .create())


    builder.route(raw_packagesMatcher()
        .handler(timingHandler)
        .handler(assetKindHandler.rcurry(PACKAGES))
        .handler(securityHandler)
        .handler(exceptionHandler)
        .handler(handlerContributor)
        .handler(negativeCacheHandler)
        .handler(partialFetchHandler)
        .handler(contentHeadersHandler)
        .handler(unitOfWorkHandler)
        .handler(proxyHandler)
        .create())

```

?

**Comment by DarthHater** [comment]
You could probably avoid the second `builder.route`, and maybe genericize the routes into one that would match on `PACKAGES` and `PACKAGES.gz` (and `PACKAGES.rds`) by doing 

`('/{path:.+}/PACKAGES{extension:.+}')`

This would create an extension variable for use in matcherState later, in case you needed to do anything special with each type of package.

**Comment by albundy83** [comment]
I have created a pull request according to your advice, but I'm not a java developer neither, so I'm not sure of what I'm doing ...
https://github.com/sonatype/nexus-repository-r/pull/13
Enjoy (or not ;-))

**Comment by cderv** [comment]
hello 

I manage to use publish in hosted repository and to install from hosted repository. 
However, my proxying R repositories is configured, but empty and I do not manage to install from it.
Still empty. 

`download.packages` is looking for `src/contrib/PACKAGES.gz`, `src/contrib/PACKAGES`  but find nothing in the proxying R Repos. (`unable to access index`.)

Seems to be the same problem as here.

Moreover, I did not understand from currently open issues how the `PACKAGES.{ext}` files are generated on the flies and shared accross repositories when using group.

@albundy83, Does you PR fixes the problem with proxy download ?

**Comment by cderv** [comment]
I think #18 fixed this issue. I have no more issue downloading from proxy, hosted or group repos for a linux environment. 
There are still some incoherence between them on the metadata but I think it is handle in another PR.

**Comment by aornatovskyy** [comment]
Looks like  ticket  could be closed

**Comment by joedragons** [comment]
I will close with 2 shout outs.  If work needs done here, please call out.
