### ISSUE TITLE
Nexus artifact/repository count 

### ISSUE THREAD

**Issue by Bkumar87** [sonatype-nexus-community/nexus-repository-r#53]
Hello Team,

I am trying to do nexus to artifactory migration and would want to know the count of Nexus artifacts/repos present to monitor once the migration is done.  

Also, Please let me know what are the things to keep in mind while doing this migration.  

Thanks, 
Bhavya

**Comment by DarthHater** [comment]
You should likely file this at: https://issues.sonatype.org/projects/NEXUS/issues, this project is mainly for R Cran repos.
