### ISSUE TITLE
Trigger Jenkins Job when pull request is created on Bitbucket 

### ISSUE THREAD

**Issue by Bkumar87** [sonatype-nexus-community/nexus-repository-r#55]
Steps I have followed so far.  

1. Configured webhook on Bitbucket 
![image](https://user-images.githubusercontent.com/49071695/62574438-8344a600-b866-11e9-8022-a38fc4584385.png)

2.  Configured Jenkins as below 
![image](https://user-images.githubusercontent.com/49071695/62574510-a8d1af80-b866-11e9-8eb2-5ae915c1253c.png)

![image](https://user-images.githubusercontent.com/49071695/62574584-d6b6f400-b866-11e9-8c92-ff56277fa7e4.png)

Once these configuration is done, I created a pull request on my project, but dont see the jenkins job trigger.  

Please help me figure out the issue with the pull request.  Thanks.

**Comment by DarthHater** [comment]
I'm a bit curious, what does this have to do with the R Cran format? Sorry if I'm missing something obvious.

**Comment by Bkumar87** [comment]
R Cran format ?

**Comment by bhamail** [comment]
It sounds like you're having trouble setting up a Jenkins job?
This community project is about adding support for the 'R' repository format to [Sonatype Nexus Repository Manager](https://www.sonatype.com/nexus-repository-oss). 
You may have better luck reaching out to the Jenkins community?
