### ISSUE TITLE
Please distribute the jar

### ISSUE THREAD

**Issue by nicorikken** [sonatype-nexus-community/nexus-repository-r#56]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Install this plugin. I wasn't able to successfully follow any of the provided instructions. If I understand correctly I first have to build the jar.

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**
By providing a jar on a mvn registry, or by providing it as a release in this GitHub project.

* **Anything else?**

**Comment by gijzelaerr** [comment]
attached you will find a zipped jar.
[nexus-repository-r-1.0.3.zip](https://github.com/sonatype-nexus-community/nexus-repository-r/files/3496046/nexus-repository-r-1.0.3.zip)

**Comment by aornatovskyy** [comment]
Fixed in the: #58
