### ISSUE TITLE
Can't compile 1.0.3 and master

### ISSUE THREAD

**Issue by gijzelaerr** [sonatype-nexus-community/nexus-repository-r#57]
hi! I'm trying to compile nexus-repository-r. I'm following the instructions in the README.

I have:
 * Ubuntu 18.04
 * maven 3.6.0
 * openjdk 11.0.4 2019-07-16

running `make clean install` gives a lot of errors:
https://gist.github.com/gijzelaerr/a093ac43c4d373abe9ef45d36b5e7e85

I wasn't sure if I actually really had to compile the code, but couldn't find a compiled version. I seem to be not alone: https://github.com/sonatype-nexus-community/nexus-repository-r/issues/56

thanks!

**Comment by aornatovskyy** [comment]
Would you please try with openjdk 8? @gijzelaerr

**Comment by gijzelaerr** [comment]
yes, that works.

**Comment by aornatovskyy** [comment]
Sure thanks for the update! 

> yes, that works, thanks! maybe the README should be updated to indicate only java 8 is supported?
Sure, thanks for the update!

**Comment by joedragons** [comment]
I went ahead and made a PR.  I think the + was errant, I'll let someone tell me I'm wrong.  Thanks for the report.

**Comment by joedragons** [comment]
Whoops, I didn't see #58 =)

**Comment by aornatovskyy** [comment]
Fixed in the: #58
